// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACR4uS6J0Xf41poK_yMszt8V6ycbIMD04',
    appId: '1:380222998663:web:402b55af7ff08b8ebfd022',
    messagingSenderId: '380222998663',
    projectId: 'food-delivery-app-c9657',
    authDomain: 'food-delivery-app-c9657.firebaseapp.com',
    storageBucket: 'food-delivery-app-c9657.firebasestorage.app',
    measurementId: 'G-FFL636NGV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNtUe1kfLefCBihpZDAWeF97Se4Dg7H0c',
    appId: '1:380222998663:android:d9260eba63c65312bfd022',
    messagingSenderId: '380222998663',
    projectId: 'food-delivery-app-c9657',
    storageBucket: 'food-delivery-app-c9657.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACR4uS6J0Xf41poK_yMszt8V6ycbIMD04',
    appId: '1:380222998663:web:d6d9a029af435174bfd022',
    messagingSenderId: '380222998663',
    projectId: 'food-delivery-app-c9657',
    authDomain: 'food-delivery-app-c9657.firebaseapp.com',
    storageBucket: 'food-delivery-app-c9657.firebasestorage.app',
    measurementId: 'G-93XEDDFJN6',
  );

}