name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # или master, проверь имя своей ветки

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # Вот тут мы чиним твои картинки и иконки
        run: flutter build web --web-renderer html --release

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: food-delivery-app-c9657  # замени на ID из настроек Firebase
